services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build: .
    volumes:
      - .:/code 
    env_file:
      - '.env'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: