services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: 1234
      - POSTGRES_DB: todo_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
     - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pg_data